name: Linting Poc

on:
    push:
        branches: [lint-poc]
    pull_request:
        branches: [lint-poc]

jobs:
    megalinter:
        name: linting checks
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v5

            - name: Run Mega-Linter
              uses: oxsecurity/megalinter/flavors/terraform@v9.1.0
              env:
                VALIDATE_ALL_CODEBASE: true
                APPLY_FIXES: MARKDOWN_MARKDOWNLINTER,YAML_YAMLLINT,TERRAFORM_TFLINT
                APPLY_FIXES_EVENT: all
                APPLY_FIXES_MODE: pull_request
                APPLY_FIXES_IF_COMMIT: 'true'
                ENABLE: MARKDOWN,YAML,TERRAFORM
                DISABLE_LINTERS: MARKDOWN_MARKDOWN_TABLE_FORMATTER,YAML_PRETTIER,YAML_V8R,TERRAFORM_FMT,TERRAFORM_TERRASCAN
