name: MegaLinter with Reviewdog Suggester
on:
  pull_request:
    branches: [main, master, lint-and-review]
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
permissions: {}
jobs:
  megalinter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run MegaLinter
        uses: oxsecurity/megalinter/flavors/terraform@v9.1.0
        env:
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: pull_request
          APPLY_FIXES_MODE: no_commit
          DISABLE_LINTERS: YAML_V8R,TERRAFORM_TERRASCAN,MARKDOWN_MARKDOWN_TABLE_FORMATTER
          FLAVOR_SUGGESTIONS: false
          ENABLE: YAML,TERRAFORM,MARKDOWN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPORTERS: github_pr_review,github_suggestions,SARIF
          REPORT_OUTPUT_FOLDER: megalinter-reports
          VALIDATE_ALL_CODEBASE: false
      - name: Archive MegaLinter reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: megalinter-reports
          path: |
            megalinter-reports
            mega-linter.log
      - name: List MegaLinter report files
        if: always()
        run: ls -l megalinter-reports || true
      - name: Suggest fixes with reviewdog
        if: always()
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: megalinter
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
